### ISSUE TITLE
What is the solution of Supermemory? How does it solve the problem?

### ISSUE THREAD

**Issue by erandow** [Dhravya/supermemory#10]
Hi,
I saw your project and I was attracted by it. You seem to find a common problem among people (especially developers) with an uncountable `to read` list. After reading the `readme`, I couldn't understand your solution to the problem actually, I reread the documentation but couldn't find the solution. 

My question is, how do you want to overcome the problem? Just by storing it in a database and starting chatting with that?

Wanna know more about what you are thinking about and what the roadmap of the project is.

Thanks.

**Comment by Dhravya** [comment]
hi! Supermemory is basically doing retrieval augmented generation. 

here's the demo video, hope it helps! https://www.loom.com/share/23b56648da3d4d8080b542a60cb9c8b6
