### ISSUE TITLE
[BUG] Input Text Box issue

### ISSUE THREAD

**Issue by ThakerKush** [Dhravya/supermemory#104]
Pressing shift + enter in the text box currently submits the prompt instead of creating a new line, the text box also allows submission of empty prompts

![PHOTO-2024-07-04-23-04-53](https://github.com/Dhravya/supermemory/assets/89926467/07fb2863-c632-4623-864b-a7546599492d)

**Comment by Dhravya** [comment]
Thanks, fixed!
