### ISSUE TITLE
Self host as API?

### ISSUE THREAD

**Issue by douglasg14b** [Dhravya/supermemory#14]
This is something that I've been wanting to play with for a long time. 

However most implementations tend to be based on a browser extension, chrome only, using a proprietary backend or paid service. This project is exciting since the back end is included!!

Are there plans for this to be "one click" self-hostable through docker/K8's, so devs can use it as a solution and build on top of it?

Of course I understand that it could just be forked and modified to fit whatever needs someone might want for it. But improving an existing project is usually better than siloing!

**Comment by Dhravya** [comment]
Yes! Absolutely. this is something i definitely want to do. A "Mempry API" that can be plugged into any app and any developer can use it. How does that sound?

Get your API key, make a project and BOOM!

**Comment by douglasg14b** [comment]
yep! However, self-hosted, meaning instead of using a 3rd party service (Say hosted by you). Devs can host this on their own hardware and integrate at their own convenience.

**Comment by leo-goss** [comment]
This would be awesome!

**Comment by Dhravya** [comment]
@leo-goss tha ms for the interest! Would it be cool if:
1. a public API is provided with limits 
2. that API can be hosted on your own cloudflare account if you need to? 

The API manages /add (chunking vector generation etc)
and /query (query the vector and get results with score IDs)

**Comment by leo-goss** [comment]
That’s exactly it! And perhaps a plug and play small javascript to add a sticky button “add to memory” to a website for instance

**Comment by Dhravya** [comment]
Very cool idea. thanks.
