### ISSUE TITLE
Firefox extension?

### ISSUE THREAD

**Issue by preetmungara** [Dhravya/supermemory#17]
Will there be a Firefox extension anytime soon?

**Comment by Dhravya** [comment]
Planned! I think firefox is compatible with the chrome extensions, can someone try to load it?

**Comment by preetmungara** [comment]
From store not able to add it.
![image](https://github.com/Dhravya/supermemory/assets/52830829/81dfe17c-951c-4d06-9a33-67323c7200ff)

**Comment by Dhravya** [comment]
Yeah, it won't work from the store. Follow these steps please:
- Go to `firefox://extensions`
- Turn on developer mode
- Then, unpack this and load it https://i.dhr.wtf/r/extension.zip
- Go to https://supermemory.dhr.wtf and click on "Extension auth" button in the bottom right

**Comment by Playye** [comment]
Loading failed. Tested both Firefox 125.0.2 (64-bit) and LibreWolf 124.0.1-1. Error:
![image](https://github.com/Dhravya/supermemory/assets/65850110/433ac85f-1449-4fb8-86eb-2d9b18ddf43d)
