### ISSUE TITLE
Deploy local vite conflict

### ISSUE THREAD

**Issue by hhwjsw711** [Dhravya/supermemory#20]
I tried to deploy the project locally, but when running the bun install command, warning: incorrect peer dependency "vite@5.2.9" appeared. This was due to the two @vitejs/plugin-react": "^4.2.1 and @crxjs /vite-plugin": "^1.0.14 caused by conflicts, how to avoid this?

**Comment by Dhravya** [comment]
hi! I had this error too, force install worked well!
