### ISSUE TITLE
Modal for extension auth flow

### ISSUE THREAD

**Issue by jeevikasirwani** [Dhravya/supermemory#22]
![image](https://github.com/Dhravya/supermemory/assets/83456541/d0a024e7-8a07-4e79-8b95-42b0e75e02aa)
the extension and auth text available on sidebar do not provide any functionality

**Comment by Dhravya** [comment]
Yeah, that's terrible UX. I'm aware of that one.

The extension auth button is one button, that basically sends your auth information to the chrome extension. It's to turn it on, that's it. 

It is functional, but does not clearly state what it does, and does not sit in the right place.

**Comment by Dhravya** [comment]
Here's the ideal solution to this: A small button, above the profile, should open up a modal that looks this: 
<img width="744" alt="image" src="https://github.com/Dhravya/supermemory/assets/63950637/e84b59b3-fe44-44c9-bdff-608491ac0066">
