### ISSUE TITLE
An error occurred during installation "bun dev" doesn't work...

### ISSUE THREAD

**Issue by luka1104** [Dhravya/supermemory#27]
Hi! I'm pretty new to bun and cloudflare. But this application is amazing so I really want to run it on local.
I followed the setupguide.md and I was able to setup until step 7.
But for step 8, when executing the following command, I encountered an issue: "bun run". During the process, there was an error message:

"$ bun dev
$ dotenv -- turbo run dev --filter=!cf-ai-backend
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn turbo ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn turbo',
  path: 'turbo',
  spawnargs: [ 'run', 'dev', '--filter=!cf-ai-backend' ]
}

Node.js v19.0.0
error: script "dev" exited with code 1"

How can I solve this error? Also, I can share the information until step 7.

**Comment by Dhravya** [comment]
Hi! 
This seems like an issue with bun. 

For the run command, you can just use `npm run dev` or directly do `turbo run dev --filter=!cf-ai-backend`

**Comment by luka1104** [comment]
Hi! Thanks for the reply!
I have solved this issue!

I was able to run with `npm run dev` but I need to install turbo...
I think the problem was the turbo was missing.
After I installed turbo `bun dev` works too.

Thanks for your help! (I'm facing another error so I'll create another issue soon...)
