### ISSUE TITLE
[Feature Enhancement] Use NextAuth for in house database to manage users

### ISSUE THREAD

**Issue by arre-ankit** [Dhravya/supermemory#30]
Now
![image](https://github.com/Dhravya/supermemory/assets/98694380/b82d048d-997a-4729-bbc8-0a6c852a13b6)

Want to build :
- A new ui to enter their email,password along with Continue with Google

Questions -
- Which db are using
- Any inputs from you to build this feature

**Comment by Dhravya** [comment]
Yes, absolutely. 
Will not do email-password. Only continue with google (if we add email-password it will bring other problems like avatar, name, etc.)

See issue #6 for design details

We use Cloudflare's D1 database

**Comment by arre-ankit** [comment]
Yaa that might be a case !
We can just change ui of page.tsx with Continue with Google button

**Comment by Dhravya** [comment]
Or better still, make a `/signin` page and change the nextauth default signin page

**Comment by arre-ankit** [comment]
Yaa sure that's good option!!

**Comment by arre-ankit** [comment]
I am not able to resolve this error after running`bun dev`
 Can anyone help me ?
![image](https://github.com/Dhravya/supermemory/assets/98694380/b1aefbca-fa6f-456f-9f05-6ad822acf0d1)

**Comment by Dhravya** [comment]
Hi! Your initial database setup seems to be incorrectly set up. 
Did you follow all steps from SETUP-GUIDE.md?

**Comment by Dhravya** [comment]
let's continue discussion in #6

**Comment by arre-ankit** [comment]
I think I have done something wrong in cloudflare I never it used it before figuring out the error!
