### ISSUE TITLE
discord?

### ISSUE THREAD

**Issue by shaayaansayed** [Dhravya/supermemory#32]
Hey there - excited about this project, so far its much more robust than the other products I've tried. 

Is there a discord or slack for folks who want to contribute seriously? Are you open to active development from others, and if so, how do you recommend the community goes about it?

**Comment by Dhravya** [comment]
Hi Shayaan! 
That's an awesome idea. I'm very swamped up with work at the moment so am not able to give a *lot* of my time to this project. 
That said, I just created this discord channel for people who want to contribute even a little bit. 
I am open to active development from others.
https://discord.gg/2X2XsKz5AU
