### ISSUE TITLE
Directly open notes from the sidebar 

### ISSUE THREAD

**Issue by Dhravya** [Dhravya/supermemory#33]
Currently, the only way to add notes is from here - 
<img width="584" alt="image" src="https://github.com/Dhravya/supermemory/assets/63950637/dca6534e-46a0-44d0-8649-9badf2485d81">

Upon recieving feedback about this, I found that the notes feature is actually very helpful and should be a button in the sidebar itself. also because the sidebar is pretty empty right now!

**Comment by Ydixit007** [comment]
Seems pretty straightforward, Can I take up on it?

**Comment by Dhravya** [comment]
Yes! Assigning it to you
