### ISSUE TITLE
Ratelimiter not working

### ISSUE THREAD

**Issue by TonsiTT** [Dhravya/supermemory#38]
Trying to deploy gives the error:

✘ [ERROR] Running configuration file validation for Pages:

    - Configuration file for Pages projects does not support "unsafe"
    
   
   Its due to the unsafe.binding for ratelimiter

**Comment by Dhravya** [comment]
Yes, you can just remove the ratelimiter field in wrangler.toml and it will work exactly the same way (without ratelimits)

**Comment by TonsiTT** [comment]
any way to retain the ratelimiter?
