### ISSUE TITLE
[bug] Doesn't provide the relevant answer

### ISSUE THREAD

**Issue by Shiva953** [Dhravya/supermemory#43]
I added some memories, and then asked a follow-up question relevant to one of them.
<img width="1398" alt="Screenshot 2024-05-12 at 5 30 24 PM" src="https://github.com/Dhravya/supermemory/assets/120790871/4369af52-ee58-42de-8f8f-1aa59e78acf3">

Instead provides some vague response(tho it quotes the relevant memory).

**Comment by Dhravya** [comment]
Hi! Thanks for pointing this out! I was experimenting with new prompts and new ways to generate responses since the last three days and this is likely one of the bad base prompts and this absolutely shouldn't happen!
