### ISSUE TITLE
Hydration failed error 

### ISSUE THREAD

**Issue by KMseven** [Dhravya/supermemory#46]
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error

Did not expect server HTML to contain a <button> in <div>.

<Home>
  <MemoryProvider>
    <Content>
      <div>
        <SessionProvider>
          <div>
            <Main>
              <AnimatePresence>
                <PresenceChild>
                  <main>
                    <div>
Call Stack
React
throwOnHydrationMismatch
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (6981:1)
popHydrationState
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (7384:1)
completeWork
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (19764:1)
completeUnitOfWork
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25963:1)
performUnitOfWork
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25759:1)
workLoopConcurrent
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25734:1)
renderRootConcurrent
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25690:1)
performConcurrentWorkOnRoot
node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24504:1)
workLoop
node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (256:1)
flushWork
node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (225:1)
MessagePort.performWorkUntilDeadline
node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (534:1)

After I login I am getting this error. I just started learning next so i am really sure what the issue is. I havent changed anything in the code

**Comment by KMseven** [comment]
<img width="1581" alt="Screenshot 2024-05-16 at 3 03 23 PM" src="https://github.com/Dhravya/supermemory/assets/10342085/16c1273a-5dc7-40a7-9a9e-4c4472aee1ec">

**Comment by Dhravya** [comment]
Yes i am aware of this, fixed and will be up in the next release!

**Comment by KMseven** [comment]
wow. You are awesome. 

@Dhravya Also in the server code we are using vectorize but its not possible to bind things like vectorize in local right 

https://docs.google.com/spreadsheets/d/1T7j7FZZO7zmkrEegzhMeMtlFPIh-efYGMc7BuenMPWY/edit#gid=1961597022
