### ISSUE TITLE
remove the default next auth sign in page with a custom one (default one's ugly)

### ISSUE THREAD

**Issue by anonthedev** [Dhravya/supermemory#6]
```
<button
          onClick={() => {
            signIn("google");
          }}
          className="flex flex-row gap-4 items-center justify-center px-8 py-4 rounded-md text-black font-semibold font-raleway bg-white"
        >
          <Image src={"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Google_%22G%22_logo.svg/768px-Google_%22G%22_logo.svg.png"} alt="" width={30} height={30} />
          Sign in with Google
        </button>
```

this button should be ok ig I've just picked it from one of my projects, I've changed the image src to some random google logo I found online.

**Comment by Dhravya** [comment]
Thanks anon! Yes, will implement it 

should be fairly easy to make a custom /signin page with a two column view - one column has this ![](https://supermemory.dhr.wtf/og-image.png) (instead of four features in a row, we can do 2x2 grid) and the other has "Sign in with google" button

**Comment by anonthedev** [comment]
yup, just be careful with the button as google has it's own guidelines so make sure to follow them
