### ISSUE TITLE
Inconsistent Border Radius under "Usecases" section 

### ISSUE THREAD

**Issue by NirbhaySirsikar** [Dhravya/supermemory#89]
![image](https://github.com/Dhravya/supermemory/assets/108933885/32f45b2a-6599-432c-ad98-24ecbec49356)

There's a Little inconsistency in border radius under usecases section.
If its intentional you can close this issue and the linked PR to this.

Those inconsistent border radius annoy me a lot 😭

**Comment by Dhravya** [comment]
h! thank you so much for raising this issue!
 this is from the older landing page, we fixed all these issues in the new one!
