### ISSUE TITLE
Importing tweets doesn't work

### ISSUE THREAD

**Issue by RhysSullivan** [Dhravya/supermemory#95]
README says to use https://chromewebstore.google.com/detail/supermemory/afpgkkipfdpeaflnpoaffkcankadgjfc?hl=en-GB&authuser=0 

![image](https://github.com/Dhravya/supermemory/assets/39114868/99a5dbe8-134e-43c0-9c50-abac98a18516)

trying to sign into that extension takes you to https://supermemory.dhr.wtf/api/auth/signin which doesn't resolve

onboarding should have a tutorial / CTA on how to import existing data

**Comment by Dhravya** [comment]
hi! 
Yeah, that's the old extension! the version 2 of the extension is under review. 
README is outdated! will fix
<img width="456" alt="image" src="https://github.com/Dhravya/supermemory/assets/63950637/da7c9990-c4b9-4f84-8383-d66ce417b2dc">

**Comment by Dhravya** [comment]
@RhysSullivan hey - the new version extension is up on the same link - 
There's one issue with it that I found after releasing, just make sure you're logged into supermemory *before* downloading it!
